###
GET http://localhost:9000/api HTTP/1.1

###
GET http://localhost:9000/api/ratings/1 HTTP/1.1
###
GET http://localhost:9000/api/favs/google-oauth2|112718355020188085224 HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "quote_id": 1,
    "rating": "5",
    "comment": "No te lo voy a negar",
    "user_info": "Kevin Collazos"
}

###
POST http://localhost:9000/api/register_fav HTTP/1.1
Content-Type: application/json

{
    "quote_id": 1,
    "quote_info": "Shut up! Shut up! Shut up!",
    "quote_author": "Skyler White",
    "user_id": "12qsadd123"
}
###
DELETE http://localhost:9000/api/favs/3 HTTP/1.1






